title: "Kelley Blackmore's Portfolio"
description: "A personal website showcasing projects, blog posts, and more."
baseurl: ""
url: "https://kelleyblackmore.github.io"
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Blog settings
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Documentation settings
collections:
  docs:
    output: true
    permalink: /docs/:title/

# Mini Projects settings
collections:
  mini_projects:
    output: true
    permalink: /mini-projects/:title/

# Social media links
social_links:
  github: "https://github.com/kelleyblackmore"
  linkedin: "https://www.linkedin.com/in/kelleyblackmore"
  twitter: "https://twitter.com/kelleyblackmore"
